### PR TITLE
EuroSCORE II archetype, guidelie and test fixture

### PR DESCRIPTION
**Pull request by isabellejensen**

### CODE REVIEW

**Comment by danielkesz** [comment]
I can't open the guideline, since it asks both for the euroscore_ii.v0 and the euroscore_ii.v1 archetypes and I only have the euroscore_ii.v1 . Can you check this?

**Comment by isabellejensen** [comment]
Now I've updated the guideline

**Comment by danielkesz** [comment]
The guideline is nice and gives the intended result, but there are some things what I would change:
-In rule "calculate y", I would add some conditions, checking whether the coefficients exist. Similarly, to "Calculate predicted mortality" I would check for the existence of y.
-Probably you could change the "insulin or diabetes" field to "Insulin-dependent diabetes" as it is very easy to misunderstand the former. I would say "yes" for this field for a type II diabetes patient, however I should say "no", since it is no IDDM (Type I).
-Probably you could also write some description to some of the fields in the archetype which are not unambiguous (I found weight of the intervention, recent MI, urgency, Extracardiac arteriopathy, Previous cardiac surgery belonging to this category).

Otherwise, everything is perfect.

**Comment by isabellejensen** [comment]
I agree with the conditions before performing the calculations. However, the editor won't allow me to check this for local variables. 

I have made updates according to your other comments. Thanks!

**Pull request merged**
